import {APIUri} from "@/api";

export default {
    "/task/firewall": {
        list: {apis: [{method: 'GET', uri: APIUri.Task.restful.list}], desc: "查看工单"},
        get: {apis: [{method: 'GET', uri: APIUri.Task.restful.get}], desc: "查看单个工单"},
        create: {apis: [{method: 'POST', uri: APIUri.Task.restful.create}], desc: "添加防火墙任务"},
        delete: {apis: [{method: 'DELETE', uri: APIUri.Task.restful.delete}], desc: "删除防火墙任务"},
        addInfos: {apis: [{method: 'POST', uri: APIUri.Task.addInfos}], desc: "获取附件"},
        geneConfig: {apis: [{method: 'POST', uri: APIUri.Task.geneConfig}], desc: "生成配置"},
        exec: {apis: [{method: 'POST', uri: APIUri.Task.exec}], desc: "执行工单"},
        syncJiraStatus: {apis: [{method: 'POST', uri: APIUri.Task.syncJiraStatus}], desc: "同步工单状态"},
        verifyPass: {apis: [{method: 'POST', uri: APIUri.Task.verifyPass}], desc: "审核工单"},
        toLeader: {apis: [{method: 'POST', uri: APIUri.Task.toLeader}], desc: "送leader审核"},
        addInfo: {apis: [{method: 'POST', uri: APIUri.Task.info.restful.create}], desc: "添加策略"},
        deleteInfo: {apis: [{method: 'POST', uri: APIUri.Task.info.restful.delete}], desc: "删除策略"},
    },
    "/task/nlb": {
        list: {apis: [{method: 'GET', uri: APIUri.Task.restful.list}], desc: "查看工单"},
        get: {apis: [{method: 'GET', uri: APIUri.Task.restful.get}], desc: "查看单个工单"},
        create: {apis: [{method: 'POST', uri: APIUri.Task.restful.create}], desc: "添加防火墙任务"},
        delete: {apis: [{method: 'DELETE', uri: APIUri.Task.restful.delete}], desc: "删除防火墙任务"},
        addInfos: {apis: [{method: 'POST', uri: APIUri.Task.addInfos}], desc: "获取附件"},
        geneConfig: {apis: [{method: 'POST', uri: APIUri.Task.geneConfig}], desc: "生成配置"},
        exec: {apis: [{method: 'POST', uri: APIUri.Task.exec}], desc: "执行工单"},
        syncJiraStatus: {apis: [{method: 'POST', uri: APIUri.Task.syncJiraStatus}], desc: "同步工单状态"},
        verifyPass: {apis: [{method: 'POST', uri: APIUri.Task.verifyPass}], desc: "审核工单"},
        toLeader: {apis: [{method: 'POST', uri: APIUri.Task.toLeader}], desc: "送leader审核"},
        addInfo: {apis: [{method: 'POST', uri: APIUri.Task.info.restful.create}], desc: "添加策略"},
        deleteInfo: {apis: [{method: 'POST', uri: APIUri.Task.info.restful.delete}], desc: "删除策略"},
    },
    "/device/firewall": {
        list: {apis: [{method: 'GET', uri: APIUri.Device.restful.list}], desc: '查看防火墙设备'},
        create: {apis: [{method: 'POST', uri: APIUri.Device.restful.create}], desc: '添加防火墙设备'},
        update: {apis: [{method: 'PUT', uri: APIUri.Device.restful.update}], desc: '更新防火墙设备'},
        delete: {apis: [{method: 'DELETE', uri: APIUri.Device.restful.delete}], desc: '删除防火墙设备'},
        updatePolicy: {apis: [{method: 'POST', uri: APIUri.Device.policy}], desc: '更新防火墙策略'},
        backup: {apis: [{method: 'POST', uri: APIUri.Device.backup}], desc: '配置备份'},
        download: {apis: [{method: 'GET', uri: APIUri.Backup.download}], desc: '配置下载'},
    },
    "/device/nlb": {
        list: {apis: [{method: 'GET', uri: APIUri.NLBDevice.restful.list}], desc: '查看负载均衡设备'},
        create: {apis: [{method: 'POST', uri: APIUri.NLBDevice.restful.create}], desc: '添加负载均衡设备'},
        update: {apis: [{method: 'PUT', uri: APIUri.NLBDevice.restful.update}], desc: '更新负载均衡设备'},
        delete: {apis: [{method: 'DELETE', uri: APIUri.NLBDevice.restful.delete}], desc: '删除负载均衡设备'},
        updatePolicy: {apis: [{method: 'POST', uri: APIUri.NLBDevice.policy}], desc: '更新负载均衡策略'},
    },
    "/policy/firewall": {
        list: {apis: [{method: 'GET', uri: APIUri.Policy.firewall.restful.list}], desc: '查看防火墙策略'},
    },
    "/policy/nlb": {
        list: {apis: [{method: 'GET', uri: APIUri.Policy.nlb.restful.list}], desc: '查看负载均衡策略'},
    },
    "/policy/firewall_nat": {
        list: {apis: [{method: 'GET', uri: APIUri.Policy.firewallNat.restful.list}], desc: '查看防火墙Nat'}
    },
    "/system/user": {
        list: {apis: [{method: 'GET', uri: APIUri.User.restful.list}], desc: '查看用户信息'},
        create: {apis: [{method: 'POST', uri: APIUri.User.restful.create}], desc: '添加用户信息'},
        update: {apis: [{method: 'PUT', uri: APIUri.User.restful.update}], desc: '更新用户信息'},
        delete: {apis: [{method: 'DELETE', uri: APIUri.User.restful.delete}], desc: '删除用户信息'},
    },
    "/system/role": {
        list: {apis: [{method: 'GET', uri: APIUri.Role.restful.list}], desc: '查看角色信息'},
        create: {apis: [{method: 'POST', uri: APIUri.Role.restful.create}], desc: '添加角色信息'},
        update: {apis: [{method: 'PUT', uri: APIUri.Role.restful.update}], desc: '更新角色信息'},
        delete: {apis: [{method: 'DELETE', uri: APIUri.Role.restful.delete}], desc: '删除角色信息'},
    },
    "/system/log": {
        list: {apis: [{method: 'GET', uri: APIUri.Log.restful.list}], desc: '查看日志信息'},
    },
    "/system/region": {
        list: {apis: [{method: 'GET', uri: APIUri.Region.restful.list}], desc: '查看网络区域信息'},
        create: {apis: [{method: 'POST', uri: APIUri.Region.restful.create}], desc: '添加网络区域信息'},
        update: {apis: [{method: 'PUT', uri: APIUri.Region.restful.update}], desc: '更新网络区域信息'},
        delete: {apis: [{method: 'DELETE', uri: APIUri.Region.restful.delete}], desc: '删除网络区域信息'},
    },
    "/tools/public_whitelist": {
        list: {apis: [{method: 'GET', uri: APIUri.PublicWhitelist.restful.list}], desc: '查看公网白名单信息'},
        create: {apis: [{method: 'POST', uri: APIUri.PublicWhitelist.restful.create}], desc: '添加公网白名单信息'},
        update: {apis: [{method: 'PUT', uri: APIUri.PublicWhitelist.restful.update}], desc: '更新公网白名单信息'},
        delete: {apis: [{method: 'DELETE', uri: APIUri.PublicWhitelist.restful.delete}], desc: '删除公网白名单信息'},
        parse: {apis: [{method: 'POST', uri: APIUri.PublicWhitelist.parse}], desc: '解析公网白名单'},
        parseAll: {apis: [{method: 'POST', uri: APIUri.PublicWhitelist.parseAll}], desc: '解析所有公网白名单'},
    },
    "/tools/invalid_policy": {
        list: {apis: [{method: 'GET', uri: APIUri.InvalidPolicy.restful.list}], desc: '查看无效策略任务信息'},
        create: {apis: [{method: 'POST', uri: APIUri.InvalidPolicy.restful.create}], desc: '添加无效策略任务信息'},
        update: {apis: [{method: 'PUT', uri: APIUri.InvalidPolicy.restful.update}], desc: '更新无效策略任务信息'},
        delete: {apis: [{method: 'DELETE', uri: APIUri.InvalidPolicy.restful.delete}], desc: '删除无效策略任务信息'},
        parse: {apis: [{method: 'POST', uri: APIUri.InvalidPolicy.parse}], desc: '无效策略解析'},
    },
    "/admin/menu": {
        list: {apis: [{method: 'GET', uri: APIUri.Menu.restful.list}], desc: '查看菜单信息'},
        create: {apis: [{method: 'POST', uri: APIUri.Menu.restful.create}], desc: '添加菜单信息'},
        update: {apis: [{method: 'PUT', uri: APIUri.Menu.restful.update}], desc: '更新菜单信息'},
        delete: {apis: [{method: 'DELETE', uri: APIUri.Menu.restful.delete}], desc: '删除菜单信息'},
        relationApi: {apis: [{method: 'POST', uri: APIUri.Menu.relationApi}], desc: '关联菜单接口'},
    },
    "/admin/api": {
        list: {apis: [{method: 'GET', uri: APIUri.Api.restful.list}], desc: '查看权限信息'},
        create: {apis: [{method: 'POST', uri: APIUri.Api.restful.create}], desc: '添加权限信息'},
        update: {apis: [{method: 'PUT', uri: APIUri.Api.restful.update}], desc: '更新权限信息'},
        delete: {apis: [{method: 'DELETE', uri: APIUri.Api.restful.delete}], desc: '删除权限信息'},
    },
    "/admin/subnet": {
        list: {apis: [{method: 'GET', uri: APIUri.Subnet.restful.list}], desc: '查看网段信息'},
        create: {apis: [{method: 'POST', uri: APIUri.Subnet.restful.create}], desc: '添加网段信息'},
        update: {apis: [{method: 'PUT', uri: APIUri.Subnet.restful.update}], desc: '更新网段信息'},
        delete: {apis: [{method: 'DELETE', uri: APIUri.Subnet.restful.delete}], desc: '删除网段信息'},
    },
    "/admin/implement_type": {
        list: {apis: [{method: 'GET', uri: APIUri.ImplementType.restful.list}], desc: '查看实施类型信息'},
        create: {apis: [{method: 'POST', uri: APIUri.ImplementType.restful.create}], desc: '添加实施类型信息'},
        update: {apis: [{method: 'PUT', uri: APIUri.ImplementType.restful.update}], desc: '更新实施类型信息'},
        delete: {apis: [{method: 'DELETE', uri: APIUri.ImplementType.restful.delete}], desc: '删除实施类型信息'},
    },
    "/admin/outbound_network_type": {
        list: {apis: [{method: 'GET', uri: APIUri.OutboundNetworkType.restful.list}], desc: '查看出向网络类型信息'},
        create: {apis: [{method: 'POST', uri: APIUri.OutboundNetworkType.restful.create}], desc: '添加出向网络类型信息'},
        update: {apis: [{method: 'PUT', uri: APIUri.OutboundNetworkType.restful.update}], desc: '更新出向网络类型信息'},
        delete: {apis: [{method: 'DELETE', uri: APIUri.OutboundNetworkType.restful.delete}], desc: '删除出向网络类型信息'},
    },
    "/admin/task_template": {
        list: {apis: [{method: 'GET', uri: APIUri.TaskTemplate.restful.list}], desc: '查看任务模板信息'},
        create: {apis: [{method: 'POST', uri: APIUri.TaskTemplate.restful.create}], desc: '添加任务模板信息'},
        update: {apis: [{method: 'PUT', uri: APIUri.TaskTemplate.restful.update}], desc: '更新任务模板信息'},
        delete: {apis: [{method: 'DELETE', uri: APIUri.TaskTemplate.restful.delete}], desc: '删除任务模板信息'},
    },
    "/admin/issue_type": {
        list: {apis: [{method: 'GET', uri: APIUri.IssueType.restful.list}], desc: '查看工单类型信息'},
        create: {apis: [{method: 'POST', uri: APIUri.IssueType.restful.create}], desc: '添加工单类型信息'},
        update: {apis: [{method: 'PUT', uri: APIUri.IssueType.restful.update}], desc: '更新工单类型信息'},
        delete: {apis: [{method: 'DELETE', uri: APIUri.IssueType.restful.delete}], desc: '删除工单类型信息'},
    },
    "/admin/task_status": {
        list: {apis: [{method: 'GET', uri: APIUri.TaskStatus.restful.list}], desc: '查看任务状态信息'},
        create: {apis: [{method: 'POST', uri: APIUri.TaskStatus.restful.create}], desc: '添加任务状态信息'},
        update: {apis: [{method: 'PUT', uri: APIUri.TaskStatus.restful.update}], desc: '更新任务状态信息'},
    },
    "/admin/nat_address": {
        list: {apis: [{method: 'GET', uri: APIUri.NatAddress.restful.list}], desc: '查看防火墙nat映射信息'},
        create: {apis: [{method: 'POST', uri: APIUri.NatAddress.restful.create}], desc: '添加防火墙nat映射信息'},
        update: {apis: [{method: 'PUT', uri: APIUri.NatAddress.restful.update}], desc: '更新防火墙nat映射信息'},
        delete: {apis: [{method: 'DELETE', uri: APIUri.NatAddress.restful.delete}], desc: '删除防火墙nat映射信息'},
    },
    "/admin/firewall_subnet": {
        list: {apis: [{method: 'GET', uri: APIUri.FirewallSubnet.restful.list}], desc: '查看防火墙网段信息'},
        create: {apis: [{method: 'POST', uri: APIUri.FirewallSubnet.restful.create}], desc: '添加防火墙网段信息'},
        update: {apis: [{method: 'PUT', uri: APIUri.FirewallSubnet.restful.update}], desc: '更新防火墙网段信息'},
        delete: {apis: [{method: 'DELETE', uri: APIUri.FirewallSubnet.restful.delete}], desc: '删除防火墙网段信息'},
    },
    "/admin/device_type": {
        list: {apis: [{method: 'GET', uri: APIUri.DeviceType.restful.list}], desc: '查看防火墙类型信息'},
        create: {apis: [{method: 'POST', uri: APIUri.DeviceType.restful.create}], desc: '添加防火墙类型信息'},
        update: {apis: [{method: 'PUT', uri: APIUri.DeviceType.restful.update}], desc: '更新防火墙类型信息'},
        delete: {apis: [{method: 'DELETE', uri: APIUri.DeviceType.restful.delete}], desc: '删除防火墙类型信息'},
    },
    "/admin/device/f5_snat_pool": {
        list: {apis: [{method: 'GET', uri: APIUri.F5SnatPool.restful.list}], desc: '查看F5SnatPool信息'},
        create: {apis: [{method: 'POST', uri: APIUri.F5SnatPool.restful.create}], desc: '添加F5SnatPool信息'},
        update: {apis: [{method: 'PUT', uri: APIUri.F5SnatPool.restful.update}], desc: '更新F5SnatPool信息'},
        delete: {apis: [{method: 'DELETE', uri: APIUri.F5SnatPool.restful.delete}], desc: '删除F5SnatPool信息'},
    },
    "/admin/nlb_subnet": {
        list: {apis: [{method: 'GET', uri: APIUri.NLBSubnet.restful.list}], desc: '查看负载均衡网段信息'},
        create: {apis: [{method: 'POST', uri: APIUri.NLBSubnet.restful.create}], desc: '添加负载均衡网段信息'},
        update: {apis: [{method: 'PUT', uri: APIUri.NLBSubnet.restful.update}], desc: '更新负载均衡网段信息'},
        delete: {apis: [{method: 'DELETE', uri: APIUri.NLBSubnet.restful.delete}], desc: '删除负载均衡网段信息'},
    },
}

